---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bosh-deployment
  - name: stemcell
  - name: release
  - name: compiled-release-repo

outputs:
  - name: compiled-release
  - name: compiled-release-repo
    path: updated-compiled-release-repo

params:
  s3_host: ""
  s3_bucket: ""
  s3_access_key_id: ""
  s3_secret_access_key: ""
  products: ""
  git_user_email: ~
  git_user_name: ~

run:
  path: bosh-deployment/ci/compiled-releases/tasks/export-release.sh
